services:
  frontend:
    build: ./frontend
    ports:
      - "8082:80"
      
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - backend-data:/usr/src/app/data  # mounted sqlite volume to persist data

volumes:
  backend-data:  # defined a volume to persist data
    driver: local
