

services:
  frontend:
    build: ./frontend
    ports:
      - "8082:80"
      
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - backend-data:/usr/src/app/data  # Mount SQLite volume to persistent directory

volumes:
  backend-data:  # Define a Docker volume for backend database persistence
    driver: local
