apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskmanager-frontend
  template:
    metadata:
      labels:
        app: taskmanager-frontend
    spec:
      containers:
        - name: taskmanager-frontend
          image: hatemnefzi/taskmanager-frontend:latest
          ports:
            - containerPort: 80
          
