on: [push, pull_request]

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -f backend/Dockerfile -t hatemnefzi/taskmanager-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t hatemnefzi/taskmanager-frontend:latest ./frontend

      - name: Push backend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-backend:latest

      - name: Push frontend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-frontend:latest

  # Test Dockerized Applications
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker Images
        run: |
          docker pull hatemnefzi/taskmanager-backend:latest
          docker pull hatemnefzi/taskmanager-frontend:latest

      - name: Run Backend Tests
        run: |
          docker run --rm hatemnefzi/taskmanager-backend:latest pytest tests/

      - name: Run Frontend Tests
        run: |
          docker run --rm hatemnefzi/taskmanager-frontend:latest npm test

      - name: Run Integration Tests
        run: |
          docker network create taskmanager-network
          docker run -d --network taskmanager-network --name backend hatemnefzi/taskmanager-backend:latest
          docker run -d --network taskmanager-network --name frontend hatemnefzi/taskmanager-frontend:latest
          curl http://backend:8080/health
          curl http://frontend:3000
          docker network rm taskmanager-network
