name: CI/CD Pipeline for TaskManager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  

  # Deploy to Minikube
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Verify Minikube Cluster
        run: |
          kubectl get pods -A

      - name: Load Docker Images into Minikube
        run: |
          minikube image load hatemnefzi/taskmanager-backend:latest
          minikube image load hatemnefzi/taskmanager-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml

      - name: Wait for Frontend Pod to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=taskmanager-frontend --timeout=120s

      - name: Wait for Backend Pod to be Ready (Extended Timeout)
        run: |
          kubectl wait --for=condition=ready pod -l app=taskmanager-backend --timeout=600s

      # Debugging: Check backend pod logs if it doesn't become ready
      - name: Check Backend Pod Logs
        run: |
          kubectl logs -l app=taskmanager-backend --tail=10

      - name: List Services
        run: kubectl get services

      - name: Test Application
        run: |
          echo "Testing application endpoints"
          curl $(minikube service taskmanager-frontend --url)
