name: CI/CD Pipeline for TaskManager

#on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t hatemnefzi/taskmanager-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t hatemnefzi/taskmanager-frontend:latest ./frontend

      - name: Push backend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-backend:latest

      - name: Push frontend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-frontend:latest

  # Deploy to Kubernetes
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none

      - name: Configure kubectl for Minikube
        run: |
          mkdir -p $HOME/.kube
          mkdir -p $HOME/.minikube
          sudo cp -r /root/.kube/* $HOME/.kube/
          sudo cp -r /root/.minikube/* $HOME/.minikube/
          sudo chown -R $USER $HOME/.kube $HOME/.minikube

      - name: Verify Minikube
        run: kubectl cluster-info

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml
