name: CI/CD Pipeline for TaskManager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -f backend/Dockerfile -t hatemnefzi/taskmanager-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t hatemnefzi/taskmanager-frontend:latest ./frontend

      - name: Push backend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-backend:latest

      - name: Push frontend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-frontend:latest

  # Test job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend: Basic test to check the environment
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm install

      - name: Run backend tests (simple check)
        working-directory: ./backend
        run: |
          echo "Running backend tests"
          npm test || echo "No backend tests available"

      # Frontend: Basic check if a simple HTML file is served
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Run frontend tests (simple check)
        working-directory: ./frontend
        run: |
          echo "Running frontend tests"
          # Simple test to check if the index.html is present
          if [ -f index.html ]; then echo "Frontend test passed"; else echo "Frontend test failed"; exit 1; fi
