name: CI/CD Pipeline for TaskManager

on:
  push:
    branches-ignore:
      
      
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  # Build and push Docker images
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t hatemnefzi/taskmanager-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t hatemnefzi/taskmanager-frontend:latest ./frontend

      - name: Push backend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-backend:latest

      - name: Push frontend Docker image to Docker Hub
        run: |
          docker push hatemnefzi/taskmanager-frontend:latest

  # Deploy to Minikube
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Verify Minikube Cluster
        run: |
          kubectl get pods -A

      - name: Load Docker Images into Minikube
        run: |
          minikube image load hatemnefzi/taskmanager-backend:latest
          minikube image load hatemnefzi/taskmanager-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml

      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=taskmanager-frontend --timeout=120s
          kubectl wait --for=condition=ready pod -l app=taskmanager-backend --timeout=120s
          

      - name: List Services
        run: kubectl get services

      - name: Test Application
        run: |
          echo "Testing application endpoints"
          curl $(minikube service taskmanager-frontend --url)

